### ISSUE TITLE
Runroom testing package 0.16

### ISSUE THREAD

**Issue by dmitryuk** [Runroom/runroom-packages#130]
The package requires Runroom/testing:"^0.16", but no such version exists. That's why developer can't install dependencies
https://github.com/Runroom/runroom-packages/blob/master/packages/sortable-behavior-bundle/composer.json
Can you make 0.16 tag for Runroom/testing?

**Comment by jordisala1991** [comment]
When developing on this bundle I do not have any issues to install deps with normal composer update, did you?

If you are trying to install unreleased version on your project, I think it is possible but never tried.

Also notice the main package should never be installed on a project, you should always install each subpackage separate.

**Comment by dmitryuk** [comment]
```
cd packages/sortable-behavior-bundle/
docker run  --volume $PWD:/app composer:2.2 install
```
I get an error:
` Root composer.json requires runroom-packages/testing ^0.16, found runroom-packages/testing[dev-master, 0.16.x-dev (alias of dev-master)] but it does not match your minimum-stability.`
What I do wrong?

**Comment by jordisala1991** [comment]
Maybe this helps you? https://github.com/Runroom/runroom-packages/pull/132

Can you check?

**Comment by dmitryuk** [comment]
Yes it helped to me. But I don't sure about other dependency packages can be downloaded with dev versions

**Comment by jordisala1991** [comment]
If you use multiple of our runoom-packages in the unstable version, all need to be unstable version, and it will work.

**Comment by jordisala1991** [comment]
Closing since the PR was merged, and the issue fixed.
